### ISSUE TITLE
Missing INSTALL, configure,... files

### ISSUE THREAD

**Issue by sr12zar** [tlwg/libthai#3]
Please supply these files so we can follow the usual ./configure, make... pattern.

**Comment by thep** [comment]
I wonder if it's possible to disable tarballs provision on GitHub, as they're not intended to be used by users at all. What you get from it is a copy of version-controlled git snapshot, where you're supposed to run `./autogen.sh` to get all the rest files.

The user-ready tarballs can be downloaded from [linux.thai.net](https://linux.thai.net/pub/thailinux/software/libthai/)

The reason is that we don't maintain auto-generated files in repository, as their contents vary with the autotools version you run.

**Comment by thep** [comment]
Meanwhile, I've added the link to official source release tarball in the release message:
https://github.com/tlwg/libthai/releases/tag/v0.1.27

**Comment by sr12zar** [comment]
Thank you. I downloaded the tar ball and build from that. All went well.
Now that is clearer on how we should build the package. Would it be
possible to explain this in INSTALL, NEWS, changelog etc. files so we know
how to build the package. Let us say, we are promoting Thai Linux with
'easy to build' approaches. ;-)

sr

**Comment by JohnAZoidberg** [comment]
You can drag-n-drop the release tarball (with auto tools already run) in the edit window of a release.
Can you please do that for https://github.com/tlwg/thpronun as well?
I can't manage to build either with my system autotools.

**Comment by thep** [comment]
> You can drag-n-drop the release tarball (with auto tools already run) in the edit window of a release.

What I wish is the possibility to drag out the GitHub-provided zip file and tarball.

> Can you please do that for https://github.com/tlwg/thpronun as well?
> I can't manage to build either with my system autotools.

Done in the last release.
